---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: slack
  name: slack


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-cfgm
  namespace: slack
data:
  slack_url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
  # proxy: proxy.squid.local:3128

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: slack-hook
  namespace: slack
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: slack
            image: manintheit/slackhook:1.0
            env:
              - name: SLACK_URL
                valueFrom:
                  configMapKeyRef:
                    name: slack-cfgm
                    key: slack_url
              #####################################################
              # - name: PROXY
              #   valueFrom:
              #     configMapKeyRef:
              #       name: slack-cfgm
              #       key: proxy
              #####################################################
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure